name: lemon_engine
description: build games using flutter canvas
version: 0.9.1
homepage: https://github.com/Jerome-Saltmarsh/dart-lemon-engine

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter





