name: lemon_engine
description: A simple loop and render library
version: 0.2.5
homepage: https://github.com/Jerome-Saltmarsh/dart-lemon-engine

environment:
  sdk: '>=2.14.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  lemon_watch: ^1.0.4
  universal_html: ^2.0.8
  positioned_tap_detector_2: ^1.0.4

