name: lemon_engine
description: build games using flutter canvas
version: 0.9.0
homepage: https://github.com/Jerome-Saltmarsh/dart-lemon-engine
publish_to: none

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter





