name: lemon_engine
description: build canvas games for the web
version: 0.3.32
homepage: https://github.com/Jerome-Saltmarsh/dart-lemon-engine

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  lemon_watch: ^1.1.0
  universal_html: ^2.0.8
  url_strategy: ^0.2.0
  shared_preferences: ^2.0.11

