name: lemon_engine
description: build canvas games for the web
version: 0.6.3
homepage: https://github.com/Jerome-Saltmarsh/dart-lemon-engine

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  lemon_watch: ^1.1.0
  universal_html: ^2.0.8
  url_strategy: ^0.2.0
  shared_preferences: ^2.0.11
  image: ^4.0.17
  window_manager: ^0.3.7


